---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "unit.name" . }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "unit.name" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "unit.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "unit.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "unit.name" . }}
    namespace: {{ .Values.namespace }}
