version: "2"
run:  
  timeout: 15m  

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - gochecknoinits
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - musttag
    - nolintlint
    - nonamedreturns
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - usestdlibvars
  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
          deny:
            - pkg: gopkg.in/satori/go.uuid.v1
              desc: Use https://github.com/gofrs/uuid instead. Satori/go.uuid is no longer maintained and has critical vulnerabilities.
    nolintlint:
      allow-unused: true
    nonamedreturns:
      report-error-in-defer: false
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: false
      no-global: ""
      context: ""
      static-msg: false
      no-raw-keys: false
      forbidden-keys:
        - level
        - msg
        - logger
        - source
        - stacktrace
        - time
      args-on-sep-lines: false
    staticcheck:
      checks:
        - all
        - '-QF1008' # not need to fix; we understand how to call nested structs
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'var-naming: don''t use an underscore in package name'
      - path: (.+)\.go$
        text: 'ST1003: should not use underscores in package names'
      - path: (.+)\.go$
        text: 'ST1005: error strings should not be capitalized'
      - path: (.+)\.go$
        text: 'error-strings: error strings should not be capitalized or end with punctuation or a newline'
      - path: (.+)\.go$
        text: 'ST1005: error strings should not end with punctuation or newlines'
      - path: (.+)\.go$
        text: 'dot-imports: should not use dot imports'
      - path: (.+)\.go$
        text: 'ST1001: should not use dot imports'
      - path: (.+)\.go$
        text: don't use `init` function
      - path: (.+)\.go$
        text: 'var-naming:'
      - path: (.+)\.go$
        text: 'ST1003: '
      - path: (.+)\.go$
        text: 'exported: type name will be used as'
      - path: (.+)\.go$
        text: 'unexported-return: exported func (.*), which can be annoying to use'
    paths:
      - test/integration
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/flant/)
    goimports:
      local-prefixes:
        - github.com/flant/
  exclusions:
    generated: lax
    paths:
      - test/integration
      - third_party$
      - builtin$
      - examples$
