FROM flant/shell-operator:latest-alpine3.12
LABEL app="shell-operator" example="203-validating-webhook"

ADD frameworks/shell/ /frameworks/shell/

# Add hooks
ADD hooks /hooks

# Compiled version of shell-operator binary
#ADD shell-operator /
