package fake

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

var v121ClusterResources = []*metav1.APIResourceList{
	{
		GroupVersion: "v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "Binding",
				Name:       "bindings",
				Verbs:      metav1.Verbs{"create"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "ComponentStatus",
				Name:       "componentstatuses",
				Verbs:      metav1.Verbs{"get", "list"},
				Group:      "",
				Version:    "v1",
				Namespaced: false,
			},
			{
				Kind:       "ConfigMap",
				Name:       "configmaps",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "Endpoints",
				Name:       "endpoints",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "Event",
				Name:       "events",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "LimitRange",
				Name:       "limitranges",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "Namespace",
				Name:       "namespaces",
				Verbs:      metav1.Verbs{"create", "delete", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: false,
			},
			{
				Kind:       "Node",
				Name:       "nodes",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: false,
			},
			{
				Kind:       "PersistentVolumeClaim",
				Name:       "persistentvolumeclaims",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "PersistentVolume",
				Name:       "persistentvolumes",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: false,
			},
			{
				Kind:       "Pod",
				Name:       "pods",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "PodTemplate",
				Name:       "podtemplates",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "ReplicationController",
				Name:       "replicationcontrollers",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "ResourceQuota",
				Name:       "resourcequotas",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "Secret",
				Name:       "secrets",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "ServiceAccount",
				Name:       "serviceaccounts",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
			{
				Kind:       "Service",
				Name:       "services",
				Verbs:      metav1.Verbs{"create", "delete", "get", "list", "patch", "update", "watch"},
				Group:      "",
				Version:    "v1",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "apiregistration.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "APIService",
				Name:       "apiservices",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "apiregistration.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "apps/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "ControllerRevision",
				Name:       "controllerrevisions",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "apps",
				Namespaced: true,
			},
			{
				Kind:       "DaemonSet",
				Name:       "daemonsets",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "apps",
				Namespaced: true,
			},
			{
				Kind:       "Deployment",
				Name:       "deployments",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "apps",
				Namespaced: true,
			},
			{
				Kind:       "ReplicaSet",
				Name:       "replicasets",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "apps",
				Namespaced: true,
			},
			{
				Kind:       "StatefulSet",
				Name:       "statefulsets",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "apps",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "events.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "Event",
				Name:       "events",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "events.k8s.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "authentication.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "TokenReview",
				Name:       "tokenreviews",
				Verbs:      metav1.Verbs{"create"},
				Group:      "v1",
				Version:    "authentication.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "authorization.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "LocalSubjectAccessReview",
				Name:       "localsubjectaccessreviews",
				Verbs:      metav1.Verbs{"create"},
				Group:      "v1",
				Version:    "authorization.k8s.io",
				Namespaced: true,
			},
			{
				Kind:       "SelfSubjectAccessReview",
				Name:       "selfsubjectaccessreviews",
				Verbs:      metav1.Verbs{"create"},
				Group:      "v1",
				Version:    "authorization.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "SelfSubjectRulesReview",
				Name:       "selfsubjectrulesreviews",
				Verbs:      metav1.Verbs{"create"},
				Group:      "v1",
				Version:    "authorization.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "SubjectAccessReview",
				Name:       "subjectaccessreviews",
				Verbs:      metav1.Verbs{"create"},
				Group:      "v1",
				Version:    "authorization.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "autoscaling/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "HorizontalPodAutoscaler",
				Name:       "horizontalpodautoscalers",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "autoscaling",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "batch/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "CronJob",
				Name:       "cronjobs",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "batch",
				Namespaced: true,
			},
			{
				Kind:       "Job",
				Name:       "jobs",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "batch",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "certificates.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "CertificateSigningRequest",
				Name:       "certificatesigningrequests",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "certificates.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "networking.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "IngressClass",
				Name:       "ingressclasses",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "networking.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "Ingress",
				Name:       "ingresses",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "networking.k8s.io",
				Namespaced: true,
			},
			{
				Kind:       "NetworkPolicy",
				Name:       "networkpolicies",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "networking.k8s.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "extensions/v1beta1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "Ingress",
				Name:       "ingresses",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1beta1",
				Version:    "extensions",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "policy/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "PodDisruptionBudget",
				Name:       "poddisruptionbudgets",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "policy",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "rbac.authorization.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "ClusterRoleBinding",
				Name:       "clusterrolebindings",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "rbac.authorization.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "ClusterRole",
				Name:       "clusterroles",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "rbac.authorization.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "RoleBinding",
				Name:       "rolebindings",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "rbac.authorization.k8s.io",
				Namespaced: true,
			},
			{
				Kind:       "Role",
				Name:       "roles",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "rbac.authorization.k8s.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "storage.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "CSIDriver",
				Name:       "csidrivers",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "storage.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "CSINode",
				Name:       "csinodes",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "storage.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "StorageClass",
				Name:       "storageclasses",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "storage.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "VolumeAttachment",
				Name:       "volumeattachments",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "storage.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "admissionregistration.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "MutatingWebhookConfiguration",
				Name:       "mutatingwebhookconfigurations",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "admissionregistration.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "ValidatingWebhookConfiguration",
				Name:       "validatingwebhookconfigurations",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "admissionregistration.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "apiextensions.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "CustomResourceDefinition",
				Name:       "customresourcedefinitions",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "apiextensions.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "scheduling.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "PriorityClass",
				Name:       "priorityclasses",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "scheduling.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "coordination.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "Lease",
				Name:       "leases",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "coordination.k8s.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "node.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "RuntimeClass",
				Name:       "runtimeclasses",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "node.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "discovery.k8s.io/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "EndpointSlice",
				Name:       "endpointslices",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1",
				Version:    "discovery.k8s.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "flowcontrol.apiserver.k8s.io/v1beta1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "FlowSchema",
				Name:       "flowschemas",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1beta1",
				Version:    "flowcontrol.apiserver.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "PriorityLevelConfiguration",
				Name:       "prioritylevelconfigurations",
				Verbs:      metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"},
				Group:      "v1beta1",
				Version:    "flowcontrol.apiserver.k8s.io",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "crd.projectcalico.org/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "HostEndpoint",
				Name:       "hostendpoints",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "BGPPeer",
				Name:       "bgppeers",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "GlobalNetworkSet",
				Name:       "globalnetworksets",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "NetworkPolicy",
				Name:       "networkpolicies",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: true,
			},
			{
				Kind:       "IPPool",
				Name:       "ippools",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "FelixConfiguration",
				Name:       "felixconfigurations",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "BGPConfiguration",
				Name:       "bgpconfigurations",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "IPAMConfig",
				Name:       "ipamconfigs",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "IPAMHandle",
				Name:       "ipamhandles",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "NetworkSet",
				Name:       "networksets",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: true,
			},
			{
				Kind:       "GlobalNetworkPolicy",
				Name:       "globalnetworkpolicies",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "IPAMBlock",
				Name:       "ipamblocks",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "BlockAffinity",
				Name:       "blockaffinities",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
			{
				Kind:       "ClusterInformation",
				Name:       "clusterinformations",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "crd.projectcalico.org",
				Namespaced: false,
			},
		},
	},
	{
		GroupVersion: "monitoring.coreos.com/v1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "ThanosRuler",
				Name:       "thanosrulers",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "monitoring.coreos.com",
				Namespaced: true,
			},
			{
				Kind:       "PodMonitor",
				Name:       "podmonitors",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "monitoring.coreos.com",
				Namespaced: true,
			},
			{
				Kind:       "Alertmanager",
				Name:       "alertmanagers",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "monitoring.coreos.com",
				Namespaced: true,
			},
			{
				Kind:       "PrometheusRule",
				Name:       "prometheusrules",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "monitoring.coreos.com",
				Namespaced: true,
			},
			{
				Kind:       "ServiceMonitor",
				Name:       "servicemonitors",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "monitoring.coreos.com",
				Namespaced: true,
			},
			{
				Kind:       "Probe",
				Name:       "probes",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "monitoring.coreos.com",
				Namespaced: true,
			},
			{
				Kind:       "Prometheus",
				Name:       "prometheuses",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1",
				Version:    "monitoring.coreos.com",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "authentication.istio.io/v1alpha1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "MeshPolicy",
				Name:       "meshpolicies",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "authentication.istio.io",
				Namespaced: false,
			},
			{
				Kind:       "Policy",
				Name:       "policies",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "authentication.istio.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "certmanager.k8s.io/v1alpha1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "Certificate",
				Name:       "certificates",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "certmanager.k8s.io",
				Namespaced: true,
			},
			{
				Kind:       "ClusterIssuer",
				Name:       "clusterissuers",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "certmanager.k8s.io",
				Namespaced: false,
			},
			{
				Kind:       "Order",
				Name:       "orders",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "certmanager.k8s.io",
				Namespaced: true,
			},
			{
				Kind:       "Issuer",
				Name:       "issuers",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "certmanager.k8s.io",
				Namespaced: true,
			},
			{
				Kind:       "Challenge",
				Name:       "challenges",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "certmanager.k8s.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "rbac.istio.io/v1alpha1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "ServiceRoleBinding",
				Name:       "servicerolebindings",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "rbac.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "ClusterRbacConfig",
				Name:       "clusterrbacconfigs",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "rbac.istio.io",
				Namespaced: false,
			},
			{
				Kind:       "ServiceRole",
				Name:       "serviceroles",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "rbac.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "RbacConfig",
				Name:       "rbacconfigs",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha1",
				Version:    "rbac.istio.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "config.istio.io/v1alpha2",
		APIResources: []metav1.APIResource{
			{
				Kind:       "instance",
				Name:       "instances",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "QuotaSpec",
				Name:       "quotaspecs",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "template",
				Name:       "templates",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "adapter",
				Name:       "adapters",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "HTTPAPISpec",
				Name:       "httpapispecs",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "attributemanifest",
				Name:       "attributemanifests",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "QuotaSpecBinding",
				Name:       "quotaspecbindings",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "handler",
				Name:       "handlers",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "rule",
				Name:       "rules",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "HTTPAPISpecBinding",
				Name:       "httpapispecbindings",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1alpha2",
				Version:    "config.istio.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "networking.istio.io/v1beta1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "ServiceEntry",
				Name:       "serviceentries",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "networking.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "Gateway",
				Name:       "gateways",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "networking.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "VirtualService",
				Name:       "virtualservices",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "networking.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "DestinationRule",
				Name:       "destinationrules",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "networking.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "Sidecar",
				Name:       "sidecars",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "networking.istio.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "security.istio.io/v1beta1",
		APIResources: []metav1.APIResource{
			{
				Kind:       "AuthorizationPolicy",
				Name:       "authorizationpolicies",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "security.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "PeerAuthentication",
				Name:       "peerauthentications",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "security.istio.io",
				Namespaced: true,
			},
			{
				Kind:       "RequestAuthentication",
				Name:       "requestauthentications",
				Verbs:      metav1.Verbs{"delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"},
				Group:      "v1beta1",
				Version:    "security.istio.io",
				Namespaced: true,
			},
		},
	},
	{
		GroupVersion: "metrics.k8s.io/v1beta1",
		APIResources: []metav1.APIResource{},
	},
}
