apiVersion: v1
kind: ConfigMap
metadata:
  name: smoke-test-cm
  labels:
    smoke-test: "true"
data:
  key: "smoke-test-value"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-to-patch
  annotations:
    smoke-test-patch: "true"
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: smoke-test-svc
spec:
  selector:
    app: smoke-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoke-test
  template:
    metadata:
      labels:
        app: smoke-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80 