---
name: 🐛 Bug report
about: Report a bug to help us improve Shell-operator
---
  <!--
               Thank you for sending a bug report! Here are some tips:

  1. Please fill out the template below to make it easier to debug your problem.
  2. If you are not sure if it is a bug or not, you can ask in Discussions.
  -->

  **Expected behavior (what you expected to happen)**:

  **Actual behavior (what actually happened)**:

  **Steps to reproduce**:
  1. ...
  2. ...
  3. ...

  **Environment**:
  - Shell-operator version:
  - Kubernetes version:
  - Installation type (kubectl apply, helm chart, etc.):

  **Anything else we should know?**:

  **Additional information for debugging (if necessary)**:

  <details><summary>Hook script</summary><br><pre>

  </pre></details>

  <details><summary>Logs</summary><br><pre>

  </pre></details>