---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-operator
  labels:
    heritage: example-204
    app: shell-operator-example-204
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-operator-example-204
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        heritage: example-204
        app: shell-operator-example-204
      annotations:
        checksum/hook: {{ .Files.Get "hooks/validating.sh" | sha256sum }}
    spec:
      containers:
      - name: shell-operator
        image: {{ .Values.shellOperator.image | quote }}
        imagePullPolicy: Always
        env:
        - name: SHELL_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VALIDATING_WEBHOOK_SERVICE_NAME
          value: {{ .Values.shellOperator.validatingWebhookServiceName | quote }}
        - name: VALIDATING_WEBHOOK_CONFIGURATION_NAME
          value: {{ .Values.shellOperator.validatingWebhookConfigurationName | quote }}
        livenessProbe:
          httpGet:
            port: 9680
            path: /healthz
            scheme: HTTPS
        volumeMounts:
        - name: validating-certs
          mountPath: /validating-certs/
          readOnly: true
      serviceAccountName: example-204-acc

      volumes:
      - name: validating-certs
        secret:
          secretName: example-204-validating-certs
