---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: monitor-pods:v3
    imagePullPolicy: Never
  serviceAccountName: monitor-pods-acc
