---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
    - name: shell-operator
      image: registry.mycompany.com/shell-operator:monitor-events
      imagePullPolicy: Always
  serviceAccountName: monitor-events-acc


