#!/usr/bin/env bash

if [[ $1 == "--config" ]] ; then
  cat <<EOF
{
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "add",
            "update"
         ],
         "selector": {
            "matchLabels": {
               "secret-copier": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "default"
            ]
         }
      }
   ]
}
EOF
else
  for secret in $(hook::context_jq -r '.[] | .resourceName')
  do
    # loop through every namespace except 'default'
    for namespace in $(kubectl get namespace -o json |
                      jq -r '.items[] |
                        select((.metadata.name == "default" | not) and .status.phase == "Active") | .metadata.name')
    do
      # copy secret with a necessary data
      kubectl -n default get secret $secret -o json | \
        jq -r ".metadata.namespace=\"${namespace}\" |
                .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
        | kubectl::replace_or_create
    done
  done
fi
