#!/usr/bin/env bash

source $WORKING_DIR/common/functions.sh

hook::config() {
  cat <<EOF
{
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "delete"
         ],
         "selector": {
            "matchLabels": {
               "secret-copier": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "default"
            ]
         }
      }
   ]
}
EOF
}

hook::trigger() {
  for secret in $(jq -r '.[] | .resourceName' $BINDING_CONTEXT_PATH)
    do
      for namespace in $(kubectl get namespace -o json |
                          jq -r '.items[] |
                            select((.metadata.name == "default" | not) and .status.phase == "Active") | .metadata.name')
      do
        kubectl -n $namespace delete secret $secret
      done
    done
}

common::run_hook "$@"
