#!/usr/bin/env bash

if [[ $1 == "--config" ]] ; then
  cat <<EOF
{
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "delete"
         ],
         "selector": {
            "matchLabels": {
               "secret-copier": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "default"
            ]
         }
      }
   ]
}
EOF
else
  for secret in $(hook::context_jq -r '.[] | .resourceName')
  do
    for namespace in $(kubectl get namespace -o json |
                        jq -r '.items[] |
                          select((.metadata.name == "default" | not) and .status.phase == "Active") | .metadata.name')
    do
      kubectl -n $namespace delete secret $secret
    done
  done
fi
