#!/usr/bin/env bash
#
# Hook with a schedule binding: sync secrets with the 'secret-copier: yes' label from the 'default' namespace to the other namespaces.
#

if [[ $1 == "--config" ]] ; then
  cat <<EOF
{
   "schedule": [
      {
         "allowFailure": true,
         "crontab": "0 3 * * *"
      }
   ]
}
EOF
else
  # Copy secrets to the other namespaces.
  for secret in $(kubectl -n default get secret -l secret-copier=yes -o name);
    do
    for namespace in $(kubectl get namespace -o json |
                        jq -r '.items[] |
                          select((.metadata.name == "default" | not) and .status.phase == "Active") | .metadata.name')
    do
      kubectl -n default get $secret -o json | \
        jq -r ".metadata.namespace=\"${namespace}\" |
                .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
        | kubectl::replace_or_create
    done
  done

  # Delete secrets with the 'secret-copier: yes' label in namespaces except 'default', which are not exist in the 'default' namespace.
  kubectl get secret --all-namespaces -o json | \
    jq -r '([.items[] | select(.metadata.labels."secret-copier" == "yes" and .metadata.namespace == "default").metadata.name]) as $secrets |
             .items[] | select(.metadata.labels."secret-copier" == "yes" and .metadata.namespace != "default" and ([.metadata.name] | inside($secrets) | not)) |
             "\(.metadata.namespace) secret \(.metadata.name)"' | \
    while read -r secret
    do
      kubectl delete -n $secret
    done
fi
